### ISSUE TITLE
Rendering Css

### ISSUE THREAD

**Issue by Ayush-vachhani** [thismatters/django-svelte#7]
Everything is working fine except that the svelte components are not rendering css.
How to fix this?

**Comment by thismatters** [comment]
Sorry for the late response here. There are a few possible issues that might cause the CSS to not load, please check into each of these:
* CSS not being generated by Svelte: Ensure that the components CSS is built and appears in the `build` directory.
* Staticfiles directory isn't accessible to Django: (this is less likely the problem since you've reported that the component itself renders; but I'll include this for anyone else who has run into this issue) Ensure that the `build` directory is permissioned correctly for the django app to access, ensure that the `STATICFILES_DIRS` setting is configured according to the docs.
* Template doesn't include a `svelte_styles` block in the head for injecting CSS: I realize that the documentation has an omission here.

If you're still trying to solve this issue please let me know.

**Comment by thismatters** [comment]
Oh, as I jump in to learn more about this issue I'm realizing that there is a bit of a design problem here. The templatetag isn't able to update the `head` of the template (even if there is a `block` there to accept the CSS), apparently the templates it uses are not rendered into the main template in the way I expected. However, this arrangement of having CSS linked in the `body` of the HTML does seem to work in some browsers.

When you inspect the page, does a stylesheet `link` element exist anywhere?

**Comment by thismatters** [comment]
Please see the updated handling of CSS in version 0.2.0! Let me know if there is any more issue.
